### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Marsi591** [tuba8890/AccountGen#3]
Hey im getting this Error when trying to Access the site
`ERROR:Start:Exception on / [GET]
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python\Python38\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python\Python38\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python\Python38\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Marsi\Desktop\source\Start.py", line 76, in index
    siteSettings = mongo.db.site.find_one({"_id": "1"})
AttributeError: 'NoneType' object has no attribute 'site'`

and when directly going to localhost:8080/login i get an unvalid oauth error

**Comment by RjManhas** [comment]
@Marsi591 one issue is due to your mongodb connection string. Can you please provide it so we can check it.

**Comment by Marsi591** [comment]
@tuba8890 @RjManhas MONGO_URI=mongodb+srv://secret:secret@cluster0.wi92so6.mongodb.net/?retryWrites=true&w=majority

**Comment by RjManhas** [comment]
I see the issue with this connection string try to remove the stuff after
the /? Part and add /site

**Comment by Marsi591** [comment]
yep it worked thx and how do i fix the discord oauth thing?

**Comment by Marsi591** [comment]
yep ok

**Comment by Marsi591** [comment]
Are you home @RjManhas ?

**Comment by RjManhas** [comment]
make sure you have your client id and secret from your discord app set right.

**Comment by Marsi591** [comment]
yea i have like it isnt hard to do that

**Comment by Marsi591** [comment]
@RjManhas can we talk via Discord its easier for me if yes add me my User is DeExplo

**Comment by Marsi591** [comment]
@RjManhas can you pls help me

**Comment by RjManhas** [comment]
what does your redirect look like and are you self hosting it?

**Comment by Marsi591** [comment]
@RjManhas Like this localhost:8080/callback/ tried it with an domain too but it's not working for me

**Comment by Marsi591** [comment]
@RjManhas I think it has something to do with the code i tried it on an other application it worked completely fine

**Comment by RjManhas** [comment]
@Marsi591 im running it right now https://account.artaxnetwork.com it works fine you just dont got it setup right. try adding this too http://localhost:8080/callback

**Comment by Marsi591** [comment]
Ok let me try

**Comment by Marsi591** [comment]
still not working😢

**Comment by Marsi591** [comment]
i made it work @RjManhas thx

**Comment by Marsi591** [comment]
@RjManhas try to create an generator

**Comment by Marsi591** [comment]
nvm was to dumb
